spring:
  redis:
    host: 192.168.254.135
    port: 6379
    password: redis
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0
  application:
    name: SpringBootDataRedis
